FROM maven:3.9.6-eclipse-temurin-17 AS build

WORKDIR /app

# Clona SOLO la rama correcta
RUN git clone --branch joshua https://github.com/YisusSlap/packet-world.git .

WORKDIR /app/backend/PacketWorldAPI

RUN mvn clean package -DskipTests

# -------------------------

FROM tomcat:9-jdk17
RUN rm -rf /usr/local/tomcat/webapps/*

COPY --from=build /app/backend/PacketWorldAPI/target/PacketWorldAPI.war \
/usr/local/tomcat/webapps/ROOT.war

CMD ["catalina.sh", "run"]
